ServerName localhost

Listen 80
DocumentRoot "/usr/local/apache2/htdocs"

AddType video/mp4 .mp4
AddType video/webm .webm
AddType image/jpeg .jpg .jpeg
AddType image/png .png
AddType image/webp .webp

<Directory "/usr/local/apache2/htdocs">
  AllowOverride None
  Require all granted
</Directory>